/**
 * IAM Policy Post-Processor
 * 
 * APPLIES IAM policies generated by the binder system to Lambda execution roles.
 * 
 * SOURCE-OF-TRUTH: The binder system (via UnifiedBinderRegistry) is the sole source
 * of truth for IAM permissions generated by bindings and event sources. This post-processor
 * is the ONLY place where policies are applied—components MUST NOT use direct grant*() calls.
 * 
 * This ensures:
 * - Consistent audit provenance (all IAM via binders)
 * - CDK-Nag compliance (policies validated by binder strategies)
 * - Least-privilege enforcement (framework-specific rules applied)
 * 
 * Note on Spec Contract vs Implementation:
 * - Spec contract (platform-bindings-spec.md): `iamStatements: PolicyStatement[]`
 * - Implementation artifact: `iamPolicies: Array<IamPolicy>` where IamPolicy = { statement, description, complianceRequirement }
 * 
 * IamPolicy is a richer implementation of the spec-level iamStatements contract.
 * The additional metadata (description, complianceRequirement) enables:
 * - Better audit trails
 * - Compliance reporting
 * - Policy documentation
 * 
 * When applying policies, we extract `policy.statement` to satisfy the CDK API.
 */

import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import type { EnhancedBindingResult } from '../platform/contracts/platform-binding-trigger-spec.js';

/**
 * Logger interface for audit trail logging
 */
interface Logger {
  debug(message: string, meta?: Record<string, any>): void;
  info(message: string, meta?: Record<string, any>): void;
  warn(message: string, meta?: Record<string, any>): void;
  error(message: string, meta?: Record<string, any>): void;
}

/**
 * Post-processor result
 */
export interface IamPolicyPostProcessorResult {
  policiesApplied: number;
  lambdaFunctionsAffected: number;
}

/**
 * IAM Policy Post-Processor
 * 
 * Processes iamPolicies from binding results and applies them to Lambda execution roles.
 */
export class IamPolicyPostProcessor {
  /**
   * Process binding results and apply IAM policies to Lambda roles
   * 
   * @param bindings - Array of binding results from resolver engine
   * @param stack - CDK stack
   * @param components - Array of components for resolving Lambda functions
   * @param logger - Optional logger for audit trail (logged policies with metadata)
   * @returns Post-processor result with statistics
   */
  static process(
    bindings: Array<{
      source: string;
      target: string;
      capability: string;
      result: EnhancedBindingResult;
    }>,
    stack: cdk.Stack,
    components: any[],
    logger?: Logger
  ): IamPolicyPostProcessorResult {
    let policiesApplied = 0;
    const affectedLambdaFunctions = new Set<string>();

    // Create a map of component name to component instance
    const componentMap = new Map<string, any>();
    for (const component of components) {
      if (component.spec?.name) {
        componentMap.set(component.spec.name, component);
      }
    }

    // Process each binding result
    for (const binding of bindings) {
      const { source, result } = binding;

      // Skip if no IAM policies
      if (!result.iamPolicies || result.iamPolicies.length === 0) {
        continue;
      }

      // Find the source component
      const sourceComponent = componentMap.get(source);
      if (!sourceComponent) {
        continue;
      }

      // Only process Lambda components (lambda-api, lambda-worker)
      const componentType = sourceComponent.getType?.();
      if (componentType !== 'lambda-api' && componentType !== 'lambda-worker') {
        continue;
      }

      // Try to get Lambda function construct
      // Lambda components register their function with handle 'lambdaFunction', 'function', or 'main'
      let lambdaFunction: lambda.Function | undefined;
      
      if (typeof sourceComponent.getConstruct === 'function') {
        // Check in order: lambdaFunction (used by lambda-worker), function, main
        lambdaFunction = sourceComponent.getConstruct('lambdaFunction') as lambda.Function | undefined;
        if (!lambdaFunction) {
          lambdaFunction = sourceComponent.getConstruct('function') as lambda.Function | undefined;
        }
        if (!lambdaFunction) {
          lambdaFunction = sourceComponent.getConstruct('main') as lambda.Function | undefined;
        }
      }

      if (!lambdaFunction) {
        // Skip if we can't find the Lambda function
        continue;
      }

      // Apply all IAM policies from this binding
      for (const policy of result.iamPolicies) {
        if (policy.statement) {
          lambdaFunction.addToRolePolicy(policy.statement);
          policiesApplied++;

          // Log applied policy with metadata for audit trail
          if (logger) {
            logger.debug(
              `Applied IAM policy to Lambda execution role`,
              {
                lambdaFunction: source,
                targetComponent: binding.target,
                capability: binding.capability,
                policyDescription: policy.description || 'No description',
                complianceRequirement: policy.complianceRequirement || 'Not specified',
                actions: policy.statement.actions,
                resources: policy.statement.resources
              }
            );
          }
        }
      }

      affectedLambdaFunctions.add(source);
    }

    return {
      policiesApplied,
      lambdaFunctionsAffected: affectedLambdaFunctions.size
    };
  }
}

