version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: backstage-postgres
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backstage -d backstage"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
