packages:
  - "apps/*"
  - "packages/*"
  - "packages/*/*"
  - "tools/*"
  - "backstage-app/*"
  - "!**/node_modules"
  - "!**/dist"
  - "!**/.nx"
  - "!**/tmp"

onlyBuiltDependencies:
  - "@swc/core"
  - nx
  - unrs-resolver
