service: test-service
owner: dev-team
complianceFramework: commercial
environment: development

components:
  - name: web-server
    type: ec2-instance
    config:
      instanceType: t3.micro
      ami:
        namePattern: 'al2023-ami-*-x86_64'
        owner: 'amazon'
      userData:
        script: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          echo "<h1>Hello from Shinobi Platform</h1>" > /var/www/html/index.html
      storage:
        rootVolumeSize: 20
        encrypted: true

  - name: app-storage
    type: s3-bucket
    config:
      bucketName: test-service-storage
      versioning: true
      encryption:
        enabled: true

governance:
  tags:
    Service: test-service
    Owner: dev-team
    Environment: ${environment}
    Compliance: commercial
    ManagedBy: shinobi
