defaults:
  logging:
    enabled: true
    retention_days: 1095
    audit_logging: true
  monitoring:
    enabled: true
    alarms:
      enabled: true
      detailed_metrics: true
  security:
    encryption:
      enabled: true
      encryption_at_rest: true
      encryption_in_transit: true
    access_control:
      least_privilege: true
      multi_factor_auth: true

  waf-web-acl:
    scope: REGIONAL
    defaultAction: block
    managedRuleGroups:
      - name: AWSManagedRulesCommonRuleSet
        vendorName: AWS
        priority: 1
        overrideAction: none
      - name: AWSManagedRulesKnownBadInputsRuleSet
        vendorName: AWS
        priority: 2
        overrideAction: none
      - name: AWSManagedRulesLinuxRuleSet
        vendorName: AWS
        priority: 4
        overrideAction: none
      - name: AWSManagedRulesUnixRuleSet
        vendorName: AWS
        priority: 5
        overrideAction: none
    logging:
      enabled: true
      logDestinationType: cloudwatch
    monitoring:
      enabled: true
      alarms:
        blockedRequestsThreshold: 250

  vpc:
    cidr: 10.0.0.0/16
    maxAzs: 3
    natGateways: 2
    flowLogsEnabled: true
    flowLogRetentionDays: 1095
    vpcEndpoints:
      s3: true
      dynamodb: true
      secretsManager: true
      kms: true
    subnets:
      public:
        cidrMask: 24
      private:
        cidrMask: 24
      database:
        cidrMask: 28

  api-gateway-http:
    cors:
      allowOrigins: []
      allowHeaders:
        ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
      allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowCredentials: false
      maxAge: 86400
    throttling:
      rateLimit: 50
      burstLimit: 100
    accessLogging:
      enabled: true
      retentionInDays: 90
      includeExecutionData: false
      includeRequestResponseData: false
    monitoring:
      detailedMetrics: true
      tracingEnabled: true
      alarms:
        errorRate4xx: 2.0
        errorRate5xx: 0.5
        highLatency: 3000
        lowThroughput: 5
    security:
      enableWaf: true
      enableApiKey: true
      requireAuthorization: true

  api-gateway-rest:
    disableExecuteApiEndpoint: true
    throttling:
      rateLimit: 200
      burstLimit: 100
    logging:
      accessLoggingEnabled: true
      retentionInDays: 365
      executionLoggingLevel: ERROR
      dataTraceEnabled: false
      metricsEnabled: true
    monitoring:
      detailedMetrics: true
      tracingEnabled: true
      thresholds:
        errorRate4xxPercent: 2
        errorRate5xxPercent: 0.5
        highLatencyMs: 2000
        lowThroughput: 5
    tracing:
      xrayEnabled: true

  s3-bucket:
    public: false
    versioning: true
    eventBridgeEnabled: false
    encryption:
      type: KMS
    security:
      blockPublicAccess: true
      requireSecureTransport: true
      requireMfaDelete: true
      denyDeleteActions: false
      tools:
        clamavScan: false
    lifecycleRules:
      - id: compliance-archival
        enabled: true
        transitions:
          - storageClass: GLACIER
            transitionAfter: 90
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
    compliance:
      auditLogging: true
      auditBucketRetentionDays: 1095
      auditBucketLifecycleRules:
        - id: fedramp-moderate-audit-retention
          enabled: true
          transitions:
            - storageClass: GLACIER
              transitionAfter: 90
            - storageClass: DEEP_ARCHIVE
              transitionAfter: 365
          expiration:
            days: 1095
      objectLock:
        enabled: false
    monitoring:
      enabled: true
      clientErrorThreshold: 5
      serverErrorThreshold: 1

  secrets-manager:
    automaticRotation:
      enabled: true
      rotationLambda:
        createFunction: true
        enableTracing: true
      schedule:
        automaticallyAfterDays: 90
    encryption:
      createCustomerManagedKey: true
      enableKeyRotation: false
    recovery:
      deletionProtection: true
      recoveryWindowInDays: 30
    replicas: []
    monitoring:
      enabled: true
      rotationFailureThreshold: 1
      unusualAccessThresholdMs: 4000
    accessPolicies:
      denyInsecureTransport: true
      restrictToVpce: true
      allowedVpceIds:
        - vpce-*
      requireTemporaryCredentials: false

  application-load-balancer:
    scheme: internet-facing
    ipAddressType: ipv4
    vpc:
      subnetType: public
      subnetIds: []
    securityGroups:
      create: true
      securityGroupIds: []
      ingress:
        - port: 443
          protocol: tcp
          cidr: 0.0.0.0/0
          description: Enforce HTTPS ingress
    accessLogs:
      enabled: true
      prefix: alb/audit/
      retentionDays: 180
      removalPolicy: retain
    listeners:
      - port: 443
        protocol: HTTPS
        sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
    targetGroups: []
    deletionProtection: true
    idleTimeoutSeconds: 60
    deploymentStrategy:
      type: single
    monitoring:
      enabled: true
      alarms:
        http5xx:
          enabled: true
          threshold: 5
        unhealthyHosts:
          enabled: true
          threshold: 1
        connectionErrors:
          enabled: true
          threshold: 2
        rejectedConnections:
          enabled: true
          threshold: 1
    hardeningProfile: fedramp-moderate
    tags:
      compliance: fedramp-moderate

  iam-policy:
    controls:
      denyInsecureTransport: true
      requireMfaForActions: []
      additionalStatements: []
    logging:
      usage:
        enabled: true
        retentionInDays: 90
        removalPolicy: destroy
        tags:
          log-type: policy-usage
          retention: 90-days
      compliance:
        enabled: true
        retentionInDays: 365
        removalPolicy: retain
        logGroupNameSuffix: compliance
        tags:
          log-type: compliance
          retention: 1-year
          compliance: fedramp-moderate
    monitoring:
      enabled: true
      detailedMetrics: true
      usageAlarm:
        enabled: true
        threshold: 1000
        evaluationPeriods: 2
        periodMinutes: 60
        treatMissingData: not-breaching
        tags:
          metric-type: security
          compliance: fedramp-moderate

  cloudfront-distribution:
    origin:
      type: s3
    defaultBehavior:
      viewerProtocolPolicy: redirect-to-https
      allowedMethods: ["GET", "HEAD"]
      cachedMethods: ["GET", "HEAD", "OPTIONS"]
      compress: true
    additionalBehaviors: []
    priceClass: PriceClass_200
    geoRestriction:
      type: none
      countries: []
    logging:
      enabled: true
      bucket: compliance-cloudfront-logs
      prefix: fedramp-moderate/
      includeCookies: false
    monitoring:
      enabled: true
      alarms:
        error4xx:
          enabled: true
          threshold: 35
          evaluationPeriods: 2
        error5xx:
          enabled: true
          threshold: 8
          evaluationPeriods: 2
        originLatencyMs:
          enabled: true
          threshold: 4000
          evaluationPeriods: 2
    hardeningProfile: hardened

  kinesis-stream:
    streamMode: provisioned
    shardCount: 2
    retentionHours: 72
    encryption:
      type: kms
      customerManagedKey:
        create: true
        enableRotation: true
    monitoring:
      enabled: true
      enhancedMetrics: true
      alarms:
        iteratorAgeMs:
          enabled: true
          threshold: 300000
        readProvisionedExceeded:
          enabled: true
          threshold: 1
        writeProvisionedExceeded:
          enabled: true
          threshold: 1
    hardeningProfile: hardened

  dynamodb-table:
    partitionKey:
      name: id
      type: string
    billingMode: provisioned
    provisioned:
      readCapacity: 10
      writeCapacity: 5
      autoScaling:
        minReadCapacity: 10
        maxReadCapacity: 100
        minWriteCapacity: 5
        maxWriteCapacity: 50
        targetUtilizationPercent: 70
    tableClass: standard
    pointInTimeRecovery: true
    timeToLive:
      enabled: true
      attributeName: ttlExpiry
    stream:
      enabled: true
      viewType: new-and-old-images
    encryption:
      type: customer-managed
      customerManagedKey:
        create: true
        enableRotation: true
    backup:
      enabled: true
      retentionDays: 30
    monitoring:
      enabled: true
      alarms:
        readThrottle:
          enabled: true
          threshold: 1
        writeThrottle:
          enabled: true
          threshold: 1
        systemErrors:
          enabled: true
          threshold: 1
    hardeningProfile: hardened

  rds-postgres:
    instance:
      engineVersion: '15.4'
      instanceType: r5.large
      allocatedStorage: 100
      multiAz: true
      deletionProtection: true
      publiclyAccessible: false
      removalPolicy: retain
    encryption:
      enabled: true
      customerManagedKey:
        create: true
        enableRotation: true
    backup:
      retentionDays: 30
      copyTagsToSnapshots: true
    monitoring:
      enhancedMonitoring:
        enabled: true
        intervalSeconds: 5
      performanceInsights:
        enabled: true
        retentionDays: 1095
        useCustomerManagedKey: true
      alarms:
        cpuUtilization:
          enabled: true
          threshold: 80
          evaluationPeriods: 3
          comparisonOperator: gte
        freeStorageSpaceBytes:
          enabled: true
          threshold: 5368709120
          evaluationPeriods: 2
          comparisonOperator: lte
        databaseConnections:
          enabled: true
          threshold: 80
          evaluationPeriods: 2
          comparisonOperator: gte
    logging:
      database:
        enabled: true
        retentionInDays: 180
        removalPolicy: retain
      audit:
        enabled: false
    rotation:
      enabled: true
      mode: single-user
      scheduleInDays: 30
    security:
      iamAuthentication: false
      enforceSsl: true
    networking:
      useDefaultVpc: true
      ingressCidrs:
        - 10.0.0.0/16
      port: 5432
    observability:
      logExports:
        - postgresql
    hardeningProfile: hardened
