defaults:
  logging:
    enabled: true
    retention_days: 1095
    audit_logging: true
  monitoring:
    enabled: true
    alarms:
      enabled: true
      detailed_metrics: true
  security:
    encryption:
      enabled: true
      encryption_at_rest: true
      encryption_in_transit: true
    access_control:
      least_privilege: true
      multi_factor_auth: true

  waf-web-acl:
    scope: REGIONAL
    defaultAction: block
    managedRuleGroups:
      - name: AWSManagedRulesCommonRuleSet
        vendorName: AWS
        priority: 1
        overrideAction: none
      - name: AWSManagedRulesKnownBadInputsRuleSet
        vendorName: AWS
        priority: 2
        overrideAction: none
      - name: AWSManagedRulesLinuxRuleSet
        vendorName: AWS
        priority: 4
        overrideAction: none
      - name: AWSManagedRulesUnixRuleSet
        vendorName: AWS
        priority: 5
        overrideAction: none
    logging:
      enabled: true
      logDestinationType: cloudwatch
    monitoring:
      enabled: true
      alarms:
        blockedRequestsThreshold: 250

  vpc:
    cidr: 10.0.0.0/16
    maxAzs: 3
    natGateways: 2
    flowLogsEnabled: true
    flowLogRetentionDays: 1095
    vpcEndpoints:
      s3: true
      dynamodb: true
      secretsManager: true
      kms: true
    subnets:
      public:
        cidrMask: 24
      private:
        cidrMask: 24
      database:
        cidrMask: 28

  api-gateway-http:
    cors:
      allowOrigins: []
      allowHeaders:
        ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
      allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowCredentials: false
      maxAge: 86400
    throttling:
      rateLimit: 50
      burstLimit: 100
    accessLogging:
      enabled: true
      retentionInDays: 90
      includeExecutionData: false
      includeRequestResponseData: false
    monitoring:
      detailedMetrics: true
      tracingEnabled: true
      alarms:
        errorRate4xx: 2.0
        errorRate5xx: 0.5
        highLatency: 3000
        lowThroughput: 5
    security:
      enableWaf: true
      enableApiKey: true
      requireAuthorization: true

  api-gateway-rest:
    disableExecuteApiEndpoint: true
    throttling:
      rateLimit: 200
      burstLimit: 100
    logging:
      accessLoggingEnabled: true
      retentionInDays: 365
      executionLoggingLevel: ERROR
      dataTraceEnabled: false
      metricsEnabled: true
    monitoring:
      detailedMetrics: true
      tracingEnabled: true
      thresholds:
        errorRate4xxPercent: 2
        errorRate5xxPercent: 0.5
        highLatencyMs: 2000
        lowThroughput: 5
    tracing:
      xrayEnabled: true

  s3-bucket:
    public: false
    versioning: true
    eventBridgeEnabled: false
    encryption:
      type: KMS
    security:
      blockPublicAccess: true
      requireSecureTransport: true
      requireMfaDelete: true
      denyDeleteActions: false
      tools:
        clamavScan: false
    lifecycleRules:
      - id: compliance-archival
        enabled: true
        transitions:
          - storageClass: GLACIER
            transitionAfter: 90
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
    compliance:
      auditLogging: true
      auditBucketRetentionDays: 1095
      auditBucketLifecycleRules:
        - id: fedramp-moderate-audit-retention
          enabled: true
          transitions:
            - storageClass: GLACIER
              transitionAfter: 90
            - storageClass: DEEP_ARCHIVE
              transitionAfter: 365
          expiration:
            days: 1095
      objectLock:
        enabled: false
    monitoring:
      enabled: true
      clientErrorThreshold: 5
      serverErrorThreshold: 1

  secrets-manager:
    automaticRotation:
      enabled: true
      rotationLambda:
        createFunction: true
        enableTracing: true
      schedule:
        automaticallyAfterDays: 90
    encryption:
      createCustomerManagedKey: true
      enableKeyRotation: false
    recovery:
      deletionProtection: true
      recoveryWindowInDays: 30
    replicas: []
    monitoring:
      enabled: true
      rotationFailureThreshold: 1
      unusualAccessThresholdMs: 4000
    accessPolicies:
      denyInsecureTransport: true
      restrictToVpce: true
      allowedVpceIds:
        - vpce-*
      requireTemporaryCredentials: false
