/**
 * Integration Tests for Security Group Rule Post-Processor
 * 
 * End-to-end tests verifying that security group rules generated by bindings
 * are properly collected and applied via CDK constructs in the full resolver pipeline.
 * 
 * Test Metadata: TP-INTEGRATION-SG-RULES-001
 * {
 *   "id": "TP-INTEGRATION-SG-RULES-001",
 *   "level": "integration",
 *   "capability": "Security group rule post-processing in full resolver pipeline",
 *   "oracle": "exact",
 *   "invariants": [
 *     "Rules are collected from binding results",
 *     "Rules are applied to target security groups via CDK constructs",
 *     "Cross-stack rules are stored in SSM Parameter Store",
 *     "Same-stack rules are applied directly"
 *   ],
 *   "fixtures": ["ResolverEngine", "UnifiedBinderRegistry", "ComponentFactory", "Logger"],
 *   "inputs": {
 *     "shape": "Service manifest with components that bind using security-group:rule capability",
 *     "notes": "Tests full pipeline from binding to rule application"
 *   },
 *   "risks": ["Mock components may not reflect real behavior", "CDK synthesis complexity"],
 *   "dependencies": ["ResolverEngine", "SecurityGroupRulePostProcessor", "CrossStackRuleManager"],
 *   "evidence": ["CDK Template assertions", "SSM Parameter Store verification", "Log output"],
 *   "compliance_refs": ["docs/tickets/security-groups/SG-006-binding-result-post-processor.md"],
 *   "ai_generated": true,
 *   "human_reviewed_by": "Platform Engineering"
 * }
 */

import * as cdk from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';
import { SecurityGroupRulePostProcessor } from '../security-group-rule-post-processor.js';
import type { EnhancedBindingResult } from '../../platform/contracts/platform-binding-trigger-spec.js';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

describe('SecurityGroupRulePostProcessor__Integration', () => {
  describe('SGPostProcessor__FullFlow__CollectsAndAppliesRules', () => {
    const metadata = {
      id: 'TP-INTEGRATION-SG-RULES-001',
      level: 'integration' as const,
      capability: 'End-to-end security group rule processing from binding to CDK construct',
      oracle: 'exact' as const,
      invariants: [
        'Rules are collected from binding results',
        'Rules are applied to target security groups via CDK constructs',
        'Same-stack rules create CfnSecurityGroupIngress/Egress',
        'Cross-stack rules are stored in SSM Parameter Store'
      ],
      fixtures: ['SecurityGroupRulePostProcessor', 'CDK Stack', 'Security Group'],
      inputs: {
        shape: 'Binding results with securityGroupRules and target SG in same stack',
        notes: 'Tests full post-processor flow with actual CDK constructs'
      },
      risks: [],
      dependencies: ['SecurityGroupRulePostProcessor', 'CrossStackRuleManager'],
      evidence: ['CDK Template assertions', 'Resource counts'],
      compliance_refs: ['docs/tickets/security-groups/SG-006-binding-result-post-processor.md'],
      ai_generated: true,
      human_reviewed_by: 'Platform Engineering'
    };

    it('SGPostProcessor__FullFlow__CollectsAndAppliesRules', () => {
      const app = new cdk.App();
      const stack = new cdk.Stack(app, 'TestStack', {
        env: {
          account: '123456789012',
          region: 'us-east-1'
        }
      });

      // Create a target security group in the stack
      const targetSecurityGroup = new ec2.CfnSecurityGroup(stack, 'TargetSG', {
        groupDescription: 'Target security group for rule application',
        vpcId: 'vpc-12345678',
        tags: [
          { key: 'Name', value: 'target-sg' },
          { key: 'resource-type', value: 'security-group' }
        ]
      });

      // Create a source security group (for peer reference)
      const sourceSecurityGroup = new ec2.CfnSecurityGroup(stack, 'SourceSG', {
        groupDescription: 'Source security group',
        vpcId: 'vpc-12345678',
        tags: [
          { key: 'Name', value: 'source-sg' },
          { key: 'resource-type', value: 'security-group' }
        ]
      });

      // Create mock components array with the target security group capability
      const mockComponents = [
        {
          getCapabilities: () => ({
            'security-group:rule': {
              securityGroupId: targetSecurityGroup.ref,
              vpcId: 'vpc-12345678'
            }
          }),
          spec: {
            name: 'target-component'
          }
        }
      ];

      // Create bindings that generate security group rules
      const bindings = [
        {
          source: 'source-component',
          target: 'target-component',
          capability: 'security-group:rule',
          result: {
            environmentVariables: {
              'SECURITY_GROUP_RULE_TARGET_SG_ID': targetSecurityGroup.ref,
              'SECURITY_GROUP_RULE_VPC_ID': 'vpc-12345678'
            },
            iamPolicies: [],
            securityGroupRules: [
              {
                type: 'ingress' as const,
                peer: { kind: 'sg' as const, id: sourceSecurityGroup.ref },
                port: { from: 443, to: 443, protocol: 'tcp' as const },
                description: 'Allow HTTPS from source'
              },
              {
                type: 'ingress' as const,
                peer: { kind: 'sg' as const, id: sourceSecurityGroup.ref },
                port: { from: 80, to: 80, protocol: 'tcp' as const },
                description: 'Allow HTTP from source'
              }
            ],
            compliance: {
              status: 'compliant' as const,
              framework: 'commercial',
              actionsTaken: []
            }
          } as EnhancedBindingResult
        }
      ];

      // Process bindings through post-processor
      const result = SecurityGroupRulePostProcessor.process(
        bindings,
        stack,
        mockComponents,
        'test-service'
      );

      // Verify post-processor results
      expect(result.rulesApplied).toBe(2);
      expect(result.securityGroupsAffected).toBe(1);
      expect(result.crossStackRules).toBe(0);

      // Synthesize and verify CDK template
      const template = Template.fromStack(stack);

      // Verify security group ingress rules were created
      template.resourceCountIs('AWS::EC2::SecurityGroupIngress', 2);

      // Verify ingress rules have correct properties
      template.hasResourceProperties('AWS::EC2::SecurityGroupIngress', {
        GroupId: { Ref: 'TargetSG' },
        SourceSecurityGroupId: { Ref: 'SourceSG' },
        IpProtocol: 'tcp',
        FromPort: 443,
        ToPort: 443,
        Description: 'Allow HTTPS from source'
      });

      template.hasResourceProperties('AWS::EC2::SecurityGroupIngress', {
        GroupId: { Ref: 'TargetSG' },
        SourceSecurityGroupId: { Ref: 'SourceSG' },
        IpProtocol: 'tcp',
        FromPort: 80,
        ToPort: 80,
        Description: 'Allow HTTP from source'
      });
    });
  });

  describe('SGPostProcessor__CrossStack__StoresInSSM', () => {
    const metadata = {
      id: 'TP-INTEGRATION-SG-RULES-002',
      level: 'integration' as const,
      capability: 'Cross-stack security group rule storage in SSM Parameter Store',
      oracle: 'exact' as const,
      invariants: [
        'Cross-stack rules are stored in SSM Parameter Store',
        'Rules are not applied directly to security groups',
        'SSM parameter names follow naming convention'
      ],
      fixtures: ['SecurityGroupRulePostProcessor', 'CDK Stack', 'SSM Parameter Store'],
      inputs: {
        shape: 'Binding results with securityGroupRules targeting SG in different stack',
        notes: 'Tests cross-stack rule handling'
      },
      risks: [],
      dependencies: ['SecurityGroupRulePostProcessor', 'CrossStackRuleManager'],
      evidence: ['SSM Parameter Store resources', 'No direct security group rules'],
      compliance_refs: ['docs/tickets/security-groups/SG-003-cross-stack-security-group-dependencies.md'],
      ai_generated: true,
      human_reviewed_by: 'Platform Engineering'
    };

    it('SGPostProcessor__CrossStack__StoresInSSM', () => {
      const app = new cdk.App();
      const stack = new cdk.Stack(app, 'TestStack', {
        env: {
          account: '123456789012',
          region: 'us-east-1'
        }
      });

      // Create mock components array WITHOUT the target security group
      // This simulates a cross-stack scenario where the target SG is in a different stack
      const mockComponents: any[] = [];

      // Create bindings that generate security group rules for a cross-stack target
      const bindings = [
        {
          source: 'source-component',
          target: 'target-component',
          capability: 'security-group:rule',
          result: {
            environmentVariables: {
              'SECURITY_GROUP_RULE_TARGET_SG_ID': 'sg-otherstack123', // SG from different stack
              'SECURITY_GROUP_RULE_VPC_ID': 'vpc-12345678'
            },
            iamPolicies: [],
            securityGroupRules: [
              {
                type: 'ingress' as const,
                peer: { kind: 'sg' as const, id: 'sg-source123' },
                port: { from: 443, to: 443, protocol: 'tcp' as const },
                description: 'Allow HTTPS from source (cross-stack)'
              }
            ],
            compliance: {
              status: 'compliant' as const,
              framework: 'commercial',
              actionsTaken: []
            }
          } as EnhancedBindingResult
        }
      ];

      // Process bindings through post-processor
      const result = SecurityGroupRulePostProcessor.process(
        bindings,
        stack,
        mockComponents,
        'test-service'
      );

      // Verify post-processor results
      expect(result.rulesApplied).toBe(0); // No direct rules applied
      expect(result.securityGroupsAffected).toBe(0);
      expect(result.crossStackRules).toBe(1); // One cross-stack rule

      // Synthesize and verify CDK template
      const template = Template.fromStack(stack);

      // Verify NO security group ingress rules were created (cross-stack)
      template.resourceCountIs('AWS::EC2::SecurityGroupIngress', 0);

      // Verify SSM parameter was created for cross-stack rule
      template.resourceCountIs('AWS::SSM::Parameter', 1);

      // Verify SSM parameter has correct properties
      // The Value is stored as a JSON string, so we check for the key properties
      const ssmResources = template.findResources('AWS::SSM::Parameter');
      const ssmParam = Object.values(ssmResources)[0] as any;
      
      expect(ssmParam.Properties.Type).toBe('String');
      expect(ssmParam.Properties.Name).toBe('/shinobi/network-rules/test-service/source-component-target-component-security-group-rule');
      expect(ssmParam.Properties.Description).toContain('Cross-stack security group rule: source-component -> target-component');
      
      // Parse and verify the JSON value
      const value = JSON.parse(ssmParam.Properties.Value);
      expect(value.targetSecurityGroupId).toBe('sg-otherstack123');
      expect(value.rule.type).toBe('ingress');
      expect(value.rule.peer.kind).toBe('sg');
      expect(value.rule.peer.id).toBe('sg-source123');
      expect(value.rule.port.from).toBe(443);
      expect(value.rule.port.to).toBe(443);
      expect(value.rule.port.protocol).toBe('tcp');
      expect(value.sourceComponent).toBe('source-component');
      expect(value.targetComponent).toBe('target-component');
    });
  });
});

