apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iam-role
  title: Iam Role
  description: Platform component for AWS IAM Role management with compliance-aware configuration
  annotations:
    platform.shinobi.dev/component-type: iam-role
spec:
  type: library
  lifecycle: experimental
  owner: group:default/platform-engineering
  system: system:default/shinobi
  metadata:
    platform:
      componentType: iam-role
      version: 1.0.0
      description: Platform component for AWS IAM Role management with compliance-aware configuration
      capabilities: []
      tags: ["aws","cdk","iam","role","platform","component"]
